In [1]:
import pandas as pd
import numpy as np

# parse_data=["FILING_DATE"]
data=pd.read_csv("E://stock_data/Monthly_Price.csv",encoding="ISO-8859-1")
data

,TRADINGITEMID,TICKERSYMBOL,PRICEDATE,OPEN,CLOSE,VOLUME,ADJ_OPEN,ADJ_CLOSE,ADJ_VOLUME,CURRENCYNAME,TRADINGSTATUS,EXCHANGENAME,IMPORTANCELEVEL,Unnamed: 13,TICKERSYMBOL_right,REGION,COUNTRY
0,2585881,AW.UN,2006-01-31,15.22000,15.10000,6872.0,15.22000,15.10000,6872.0,Canadian Dollar,Active,The Toronto Stock Exchange,112.0,0,AW.UN,United States and Canada,Canada
1,2585881,AW.UN,2006-02-28,15.29000,15.49000,5921.0,15.29000,15.49000,5921.0,Canadian Dollar,Active,The Toronto Stock Exchange,112.0,0,AW.UN,United States and Canada,Canada
2,2585881,AW.UN,2006-03-31,15.91000,15.50000,4580.0,15.91000,15.50000,4580.0,Canadian Dollar,Active,The Toronto Stock Exchange,112.0,0,AW.UN,United States and Canada,Canada
3,2585881,AW.UN,2006-04-28,15.29000,15.25000,17563.0,15.29000,15.25000,17563.0,Canadian Dollar,Active,The Toronto Stock Exchange,112.0,0,AW.UN,United States and Canada,Canada
4,2585881,AW.UN,2006-05-31,15.79000,15.46000,7900.0,15.79000,15.46000,7900.0,Canadian Dollar,Active,The Toronto Stock Exchange,112.0,0,AW.UN,United States and Canada,Canada
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6199678,1823875816,NOG,2022-10-31,0.02020,0.02500,268.0,0.02020,0.02500,268.0,British Pound,Active,London Stock Exchange,59.0,51451,NOG,Europe,United Kingdom
6199679,1823875816,NOG,2022-11-30,0.02500,0.02245,3946.0,0.02500,0.02245,3946.0,British Pound,Active,London Stock Exchange,59.0,51451,NOG,Europe,United Kingdom
6199680,1823875816,NOG,2022-12-30,NaN,0.02750,NaN,NaN,0.02750,NaN,British Pound,Active,London Stock Exchange,59.0,51451,NOG,Europe,United Kingdom
6199681,1823875816,NOG,2023-01-31,NaN,0.02900,NaN,NaN,0.02900,NaN,British Pound,Active,London Stock Exchange,59.0,51451,NOG,Europe,United Kingdom
6199682,1823875816,NOG,2023-02-27,0.19675,0.19250,9667.0,0.19675,0.19250,9667.0,British Pound,Active,London Stock Exchange,59.0,51451,NOG,Europe,United Kingdom

In [3]:
US_data=data[data["COUNTRY"]=="United States"]
US_data.reset_index(inplace=True)
US_data.to_csv("D://stock_data/us_stock.csv",index=0)